addons:
  ssh_known_hosts: bitbucket.org
before_install:
- openssl aes-256-cbc -pass "pass:$SSH_SECRET" -in ./fastlane/travis_key.enc -out
  ~/.ssh/id_rsa -d -a
- chmod 600 ~/.ssh/id_rsa
- cat ./fastlane/travis_key.pub > ~/.ssh/id_rsa.pub
- chmod 600 ~/.ssh/id_rsa.pub
- fastlane --version
language: objective-c
osx_image: xcode7.2
script:
- fastlane build
env:
  matrix:
  - FASTLANE_ENV=both
  global:
  - secure: tFsVe+z4G0EMv7Qr+rvjPnnlfC3d6KHTK2YgzVBcC9AdoBArF09R33j8CNKjJeKOUTE0uBcooXjU6oJ7v1Ag3dUBCD//mB2f/w5WIxyqVhb+kmvqq+zKHHU3rN/wGVt6UJzcj/w9mLIyF4OFIeHIUZwcsr0C6veZh+1XkD1gZLpXZSS6HeBkS2PV5j5LmurQkzHQdBBg7+xw3oy8HDutbgg4YdVQUk0dVqGEIt7p0dqD0yPWFKrlQUdIoZnH5xiSO6KF2Fcvcn/hqQIglM8poCJkg+3j4/e7EMbPNpair49F+B1yT5z692NggQKuAiA5COkT+ZDIcOLTM0R8G1pJ006KfUqY9XAJnb+sB9LRjq22NG8zy5lNV4R4rFR1lbIrMkR4ZfHINow72fptH+IZyd17b7RYvFnVc2/SJAo4UxphlkbQx/2a2C14xEfEg4iTC7nGDuioj+Bxf+JqGsozmr0CDxv7jAbMzQYLzDI57epYiuQ27WTD9gK3bQxydegvW0+Kp1yecgWepsJyHAttgUQGlDs2cZcDSzlEMClmV/ep2qwjvLWmZ69Ql5WGpLiVz13Z2LdXL8PaWL2teLq9aCdQUmb0jeXkXDo70PEEJgevEoyv8V1JeyX4oaF13wZcIBw98i0GmnoE8SqCM4IDT3b3rEA2jcrNaFo+BTGgMt4=
  - secure: Y7GpnjOr+5WmbTvUkF2159a8WYCjIH239r/wE/lESQgR2kSw/+7/Ff22TXU6lAO+5SymRkBiGvpX7FoIbT5CNbQTf3eH2g1RGpjU+Mki0g5VNRaRn+L8QVKU32UnNK0dZu46Uz1v8HcnRgF06kDk7OURdToCr1Rl02U/knobBbfh0keKe0rK6KF6zkInive3c14zNhF+ky00ysMc9q6hcV2F7I9Q7Ek7xQFulodDm+35Lp7f3TuRbvvhHL0isEaOK7AqQKTaXEfk9nvv7cX+9ICZM7uoAeodj5cef1Qx8JY1GUjipFUEy3Bkxl1M9Aa+9WgpUOKmnDszaFmHphtj3gZhTW5q76ZldWbqRgEzRwjTaDyx+ngaGopKZSzlleGzOpdCIi3HtltNeKbQmI3sCMwCTx1PH2Axb+v063MKVCaAcKTJZ3/PqLdK2jcpeCyg1aNjCg8AWS8TveZXK49yRIl4+tGp9rwg1PbTVmguYth7lp+Mw9icblZMMvaYtRIOq9apW1BzS9BbWYkLTi966o57urd/PH1rFS+KlC5J+0JrxBDZPRnZ6TGl2KVpkoYwi/nm3If0wuAN9eBPhH8CCzlUePDwvwqrEm6FkvhBHKGt8519Lf+Ms582W0dtNdvfGC9UJ/eTBQsa2bbbVdgWzSoEI2fYymaSmVJCcgP0FJQ=
  - secure: xB0JKJVQJCOWlIxyXm7NMyVLcJQPd9mmUgmYcE6hPJ/zh/JqzARoVKi2ox9idFo7GROx2KP0XodP9+hQ9Rl5/FBwKjT3BBa16wRBd3uFQ4fJRG9OTaImhM2g/GNlxmMhx5GMtXdyVh38Bv5sIflrARwG8toXSZw9FDFfBh7vFnTeCn+OCGbX4RNl8d/JxJQbflUEiaKuHaeL1w70iTvMYaxqRZD4WAsRDL6xVNpPp4b+djN6kkLO7MtOP1+3KfblfrWy4YD45GZ7OpBwb7Zv5I+SMVTfJFOIthUYtZNqF9coRTTwvw2a5YlbMyO0z8cdQBQVXNi+JvJrqhmfwB4OJ4Q2jPTcNZXqaY3hzektB5aImGP6GDkWJZzXE4CJozTUaaNTn/rJHH7PrZByuD13R+JQnHEAYghkQ/UHU9UF4SU5m9J2b8wpBNZgrNwFNXoRB9KoaZtWwf7Su1a559SILw7aT2qsXGWHf4QyPS3bMQh0h2lvNFg1jnVB4kIZengNk3S9PeA97GGW/9f7EcimmHFUOe4ZXiMgOkJg+HOFYeeNluHgugn793iQGv3Qnvn0H0wg8JNdFVYi8E7s7pNqO8YvSPOQXQPoRD5GSjL8sl9svExcQ0Wv4unUw0FgrJ/POwlTssbRy+Mj98IGhoh0dOlnDKKZe104ZrZm+ZtXwwQ=
